# Generated by Django 3.2.7 on 2021-10-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsdb',
            options={'verbose_name': 'Ивент', 'verbose_name_plural': 'Ивенты'},
        ),
        migrations.AlterField(
            model_name='eventsdb',
            name='event_image',
            field=models.ImageField(upload_to='image_event/', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='eventsdb',
            name='event_text',
            field=models.CharField(max_length=100, verbose_name='описание'),
        ),
    ]
